name: Request Access
description: Demander l'accès write pour contribuer avec previews automatiques
title: "Request access: @"
labels: ["access request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Demande d'accès Write

        CineMatch utilise une infrastructure AWS sponsorisée par Umans AI. L'accès **write** te permet de créer des branches et bénéficier des **previews automatiques** sur chaque PR.

        > ⚠️ **Note** : L'accès ne donne pas les droits AWS — tu ne pourras pas modifier l'infrastructure Terraform ou voir les secrets.

  - type: input
    id: github_username
    attributes:
      label: GitHub Username
      description: Ton identifiant GitHub
      placeholder: "@votre-username"
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: Expérience (optionnel)
      description: Dis-nous en un peu plus sur ton parcours et ce que tu aimerais apprendre/apporter
      placeholder: |
        - Stack que tu connais (Python, React, etc.)
        - Ce qui t'intéresse dans le projet
        - Ce que tu aimerais apprendre
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: J'ai compris
      options:
        - label: J'ai lu [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md)
          required: true
        - label: Je comprends que l'infrastructure AWS est gérée exclusivement par Umans AI
          required: true
