"""Add region and provider_id to rooms

Revision ID: e5d9a3b1c4f2
Revises: cdc82f99bace
Create Date: 2026-03-06

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d9a3b1c4f2'
down_revision: Union[str, None] = 'cdc82f99bace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('region', sa.String(length=2), nullable=True))
    op.add_column('rooms', sa.Column('provider_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'provider_id')
    op.drop_column('rooms', 'region')
    # ### end Alembic commands ###
